[versions]
kotlin = "2.2.21"
agp = "8.13.1"
android-min-sdk = "21"
android-compile-sdk = "36"
java = "21"
ktlint = "14.0.1"
maven-publish = "0.35.0"
mockk = "1.14.7"

[libraries]
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods" , version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
